#################################################################################################################
# Create a multisite zonegroup for a collection of object stores
#  kubectl create -f object-realm.yaml
#################################################################################################################

apiVersion: ceph.rook.io/v1
kind: CephObjectZoneGroup
metadata:
  name: zonegroup-a
  namespace: rook-ceph
spec:
  realm: realm-a
