#################################################################################################################
# Create a multisite realm for a collection of object stores
#  kubectl create -f object-realm.yaml
#################################################################################################################

apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  name: realm-a
  namespace: rook-ceph
